# .github/workflows/daily_update.yml
# 這個 GitHub Actions 工作流程會「每天自動」執行數據更新腳本

name: Scheduled - Daily Data Update to R2

on:
  schedule:
    # 每天執行一次 (UTC 時間 00:00，約等於台灣時間早上 8 點)
    - cron: '0 0 * * *'

jobs:
  update-daily-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data update script to R2
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: python update_data_to_r2.py
