name: Update Stock Data

on:
  workflow_dispatch: # 允許手動觸發
  schedule:
    - cron: '0 8 * * *' # 每日午夜 (UTC) 執行，約為台灣時間早上8點

permissions:
  contents: write # 允許對倉庫內容進行寫入操作

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 修改此處，使用專為 Actions 準備的依賴檔案
          pip install -r requirements_actions.txt

      - name: Run data update script
        run: python update_data.py

      - name: Commit and push data to data branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b temp-data-branch
          git add -f data/
          if ! git diff --staged --quiet; then
            git commit -m "chore: 自動更新股票數據"
            git push -f origin temp-data-branch:data
            echo "數據已成功推送到 data 分支。"
          else
            echo "數據無變動，無需提交。"
          fi
